### ISSUE TITLE
the letsbuild jenkens page for this does not mention the requirement for that libsdisguses plugin

### ISSUE THREAD

**Issue by ghost** [PseudoKnight/CHDisguises#1]
title explains the issue. the Jenkins page here https://letsbuild.net/jenkins/job/CHDisguises/ does not bring up that libdsisguuse is required anywhere. dont know if that is in your control though. i also think the readme here should say that its a requirement.
the page makes it appear as if it can do all the disguise work by itself. so i was disappointed to find that i would have to buy and install that proprietary trash plugin. I don't mind paying for plugins (as long as i dont have to buy from spigotmc) but i only wanna use open source plugins. so i think that the dependencies should be stated more clearly.

**Comment by ghost** [comment]
#2 made a pull request for it

**Comment by PseudoKnight** [comment]
You can actually use the free version of the plugin (along with its limitations) with this extension. One of the reasons I haven't put more work into this is because the plugin pushes users to buy the premium version.

https://www.spigotmc.org/resources/libs-disguises-free.81/

Since the extension is not implementation specific in its usage, I could move it to a different disguise plugin or support multiple disguise plugins.

**Comment by PseudoKnight** [comment]
Fixed. Also, see #3
